### PR TITLE
Fixed connection bug

### PR DESCRIPTION
**Pull request by JKHeadley**
This is a fix for #205

### CODE REVIEW

**Comment by Gattermeier** [comment]
Is this under consideration?

**Comment by mtharrison** [comment]
They should be the same:

```js
WebSocket.OPEN === new WebSocket('ws://localhost:8126/').OPEN
true
```

**Comment by JKHeadley** [comment]
@mtharrison they are the same when I run the client in Node, but not in the browser.

**Comment by JKHeadley** [comment]
I've actually had to swap all instances of `Client.Websocket.OPEN` for `this._ws.OPEN` in order for the client to work in the browser. I was having many issues but this change fixed all of them.

**Comment by mtharrison** [comment]
Alternatively can you please post an example/instructions on how to replicate this issue? Maybe a mini-repo/gist would be good. As you're the only one reporting this bug so far and I cannot replicate it so far, I'm assuming an issue on your end for now.

**Comment by JKHeadley** [comment]
@mtharrison thanks for the feedback.

As an update, I ran your snippet in the console and got the same results you did. I also ran a jsfiddle with:
```javascript
console.log("EQUAL:", WebSocket.OPEN === new WebSocket('ws://localhost:8125/').OPEN)
```

Which output `true`. However, running the same line of code within `lib/client.js` outputs `false`. The results were the same with both chrome (` Version 63.0.3239.132 (Official Build) (64-bit)`) and firefox (` 58.0.1 (64-bit)`).

I will try to look deeper as to why this is only an issue within the `nes` code, but any help investigating would be appreciated.

@Gattermeier just curious, are you experiencing the same issue?

**Comment by JKHeadley** [comment]
Another update, it looks like if I run code in the console that my nes app is running, I run into the same issues. Here is a clip if it helps:

screen shot 2018-02-05 at 10 30 53 am

**Comment by mtharrison** [comment]
Something is overwriting `WebSocket.OPEN`, it should be a simple constant. Maybe an extension, or another library. Try opening the app in a different browser or remove other dependencies until you find it.

**Comment by mtharrison** [comment]
This person had the exact same issue and it was a Chrome extension doing nasty stuff: https://github.com/thoov/ember-websockets/issues/56

**Comment by JKHeadley** [comment]
@mtharrison thanks again for the feedback and insights. That's probably what's going on, although it's a bit confusing to me since its happening both in Chrome and Firefox.

However, given that this is happening for me in multiple browsers, and it has appeared once before on another issue, is there any reason why my proposed fix would be a bad idea? 

Thanks again for your help.

**Comment by JKHeadley** [comment]
P.S. big fan of your hapi articles btw. They've helped me out on multiple occasions 👍

**Comment by mtharrison** [comment]
I'm not opposed to your change per-se but it should not be necessary. If it is something like a extension that's breaking the web then we shouldn't be expected to fix nes because of it.

I would really like to understand the problem first if there is one. I'd love to get my hands on or see a workable example first though. Do you have time to put one together? It would ideally be 2 files: a server (js file) and a client (html) that has none of your application's specific stuff in it but still shows this bug. That would help to advance this hugely.

**Comment by JKHeadley** [comment]
Ok, understandable. I'll try to look into the root cause and come up with an example.

**Comment by JKHeadley** [comment]
Based on your suggestions I looked into any outside interference from plugins/extensions and discovered the issue was being caused by the [pace](https://github.com/HubSpot/pace) plugin. I removed the plugin for a fix since it was already a little buggy. Thanks for you help in figuring this out!

**Pull request closed without merging**
