### PR TITLE
Promisify Client API

### PR DESCRIPTION
**Pull request by gillesdami**
Hi,

I love hapijs/nes, however the Client API based on callbacks doesn't match any more the style of most framework. I mean to use nes Client in sagas, with async/await or just with simple Promises you often end up wrapping the API in a not so fancy way...
So I "promisified" the Client API in a fully backward compatible way. 
I think this is an improvement the community may like, tell me what you think about it  !

### CODE REVIEW

**Comment by hueniverse** [comment]
I don't mind it but I don't want another dependency. Instead, if you want to rework this to use the same pattern hapi uses, I will accept that. You can see how hapi does it here:
https://github.com/hapijs/hapi/blob/master/lib/promises.js
https://github.com/hapijs/hapi/blob/master/lib/server.js#L184-L186

**Comment by gillesdami** [comment]
Indeed it would be better but the callback must be function(err, result) to work with hapi wrap. 
client.request does not respect this syntax (function(err, payload, statusCode, headers))

**Comment by hueniverse** [comment]
Then you need to force multiple arguments into some kind of structure.

**Comment by hueniverse** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
