### PR TITLE
switch to validate and other package updates

### PR DESCRIPTION
**Pull request by lloydbenson**

### CODE REVIEW

**Comment by lloydbenson** [comment]
Looks like some of test scenarios are not passing so I'll hold off on this.

**Comment by hueniverse** [comment]
Tests are flaky. Sometimes need to retry on travis.

**Comment by cjihrig** [comment]
@lloydbenson I restarted the failing jobs, and the CI is now green.

**Comment by lloydbenson** [comment]
Thanks @cjihrig and @hueniverse.

**Pull request merged**
